e-commerce/src/Entity/CartOrder.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CartOrderRepository")
 */
class CartOrder
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="smallint")
     */
    private $items_total;

    /**
     * @ORM\Column(type="integer")
     */
    private $items_price_total;

    /**
     * @ORM\Column(type="integer")
     */
    private $price_total;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CartOrderItem", mappedBy="order")
     */
    private $cartOrderItems;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CartDiscount", inversedBy="cartOrders")
     */
    private $discount;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="cartOrders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

//    public function __toString() {
//        return "some string representation of your object";
//    }

    public function __construct()
    {
        $this->cartOrderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getItemsTotal(): ?int
    {
        return $this->items_total;
    }

    public function setItemsTotal(int $items_total): self
    {
        $this->items_total = $items_total;

        return $this;
    }

    public function getItemsPriceTotal(): ?int
    {
        return $this->items_price_total;
    }

    public function setItemsPriceTotal(int $items_price_total): self
    {
        $this->items_price_total = $items_price_total;

        return $this;
    }

    public function getPriceTotal(): ?int
    {
        return $this->price_total;
    }

    public function setPriceTotal(int $price_total): self
    {
        $this->price_total = $price_total;

        return $this;
    }

    /**
     * @return Collection|CartOrderItem[]
     */
    public function getCartOrderItems(): Collection
    {
        return $this->cartOrderItems;
    }

    public function addCartOrderItem(CartOrderItem $cartOrderItem): self
    {
        if (!$this->cartOrderItems->contains($cartOrderItem)) {
            $this->cartOrderItems[] = $cartOrderItem;
            $cartOrderItem->setOrderId($this);
        }

        return $this;
    }

    public function removeCartOrderItem(CartOrderItem $cartOrderItem): self
    {
        if ($this->cartOrderItems->contains($cartOrderItem)) {
            $this->cartOrderItems->removeElement($cartOrderItem);
            // set the owning side to null (unless already changed)
            if ($cartOrderItem->getOrderId() === $this) {
                $cartOrderItem->setOrderId(null);
            }
        }

        return $this;
    }

    public function getDiscount(): ?CartDiscount
    {
        return $this->discount;
    }

    public function setDiscount(?CartDiscount $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

e-commerce/src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email',EmailType::class,['attr' => ['placeholder' => 'title.user_mail'] ])
            ->add('surname', TextType::class,['attr' => ['placeholder' => 'title.user_surname'] ])
            ->add('lastname',TextType::class,['attr' => ['placeholder' => 'title.user_lastname'] ])
            ->add('gender', ChoiceType::class,array(
                    'choices' => [
                        'title.user_gender_female' => 'title.user_gender_female',
                        'title.user_gender_male' => 'title.user_gender_male',
                    ])
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

e-commerce/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\CartOrder;
use App\Entity\CartOrderItem;
use App\Entity\PasswordUpdate;
use App\Form\PasswordUpdateType;
use App\Form\ProfileType;
use App\Repository\CartOrderRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * Class ProfileController
 * @package App\Controller
 */
class ProfileController extends AbstractController
{
    /**
     * @param Request $request
     * @param ObjectManager $manager
     * @param UserPasswordEncoderInterface $encoder
     * @return Response
     */
    public function editPassword(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder)
    {
        $user = $this->getUser();
        $passwordUpdate = new  PasswordUpdate();
        $formPassword = $this->createForm(PasswordUpdateType::class, $passwordUpdate);
        $formPassword->handleRequest($request);

        if ($formPassword->isSubmitted() && $formPassword->isValid()){
            if (!password_verify($passwordUpdate->getOldPassword(), $user->getPassword())){
                $this->addFlash(
                    'warning',"Impossible de changer le mot de passe !"
                );
            }else{
                $newPassword = $passwordUpdate->getNewPassword();
                $hash = $encoder->encodePassword($user, $newPassword);

                $user->setPassword($hash);
                $manager->persist($user);
                $manager->flush();
                $this->addFlash(
                    'success',"Votre mdp est été modifié"
                );
            }
        }

        return $this->render('profile/password.html.twig', [
            'controller_name' => 'ProfileController',
            'formPassword' => $formPassword->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function editPersonal(Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }

        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView()
        ]);
    }

    /**
     * @return Response
     */
    public function getBill()
    {
        $user = $this->getUser();
        $invoices = $this->getDoctrine()->getRepository(CartOrder::class)->findBy(['user' => $user]);

        return $this->render('profile/invoice_index.html.twig', [
            'controller_name' => 'ProfileController',
            'invoices' => $invoices
        ]);
    }

    /**
     * @Security("is_granted('ROLE_USER') and user == cartOrder.getUser()", message="Cette facture n'est pas la votre !")
     * @param $id
     * @param CartOrderRepository $cartOrderRepository
     * @param CartOrder $cartOrder
     * @return void
     */
    public function downloadInvoice($id, CartOrderRepository $cartOrderRepository, CartOrder $cartOrder)
    {
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

//        $invoice = $this->getDoctrine()->getRepository(CartOrder::class)->findOneBy(['id' => $id]);
        $invoice = $cartOrderRepository->findOneBy(['id' => $id]);
        $items = $this->getDoctrine()->getRepository(CartOrderItem::class)->findBy(['order' => $invoice]);

        $html = $this->renderView('profile/_invoice.html.twig', [
            'invoice' => $invoice,
            'items' => $items
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');
        // Render the HTML as PDF
        $dompdf->render();
        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
    }
}

e-commerce/templates/profile/_invoice.html.twig
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Facture du {{ invoice.createdAt|date('d/M/Y') }}</title>

    <style>
        header h1 { background: #000; border-radius: 0.25em; color: #FFF; margin: 0 0 1em; padding: 0.5em 0;text-align: center; }
        h1 { font: bold 100% sans-serif; letter-spacing: 0.5em; text-align: justify; text-transform: uppercase; }
        aside h1 { border: none; border-width: 0 0 1px; margin: 0 0 1em; }
        aside h1 { border-color: #999; border-bottom-style: solid; }

        .invoice-box {
            max-width: 800px;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, .15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
        }

        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }

        .invoice-box table tr td:nth-child(2) {
            text-align: right;
        }

        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.top table td.title {
            font-size: 45px;
            line-height: 45px;
            color: #333;
        }

        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }

        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.item td{
            border-bottom: 1px solid #eee;
        }

        .invoice-box table tr.item.last td {
            border-bottom: none;
        }

        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }

        /** RTL **/
        .rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }

        .rtl table {
            text-align: right;
        }

        .rtl table tr td:nth-child(2) {
            text-align: left;
        }
    </style>
</head>

<body>

<header>
    <h1>Facture</h1>
</header>
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
        <tr class="top">
            <td colspan="2">
                <table>
                    <tr>
                        <td class="title">
{#                            <img src="https://www.sparksuite.com/images/logo.png" style="width:100%; max-width:300px;">#}
                        </td>
                        <td>
                            Facture #: 123<br>{{ invoice.createdAt|date('d/M/Y')}}
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <table>
        <tr class="information">
            <td colspan="2">
                <table>
                    <tr>
                        <td>Sparksuite, Inc.<br></td>
                        <td>{{ invoice.user.gender }} {{ invoice.user.surname }} {{ invoice.user.lastname }}<br>{{ invoice.user.email }}<br></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table>
        <tr class="heading">
            <td style="text-align: center">Produit</td>
            <td style="text-align: center">Prix unitaire</td>
            <td style="text-align: center">Quantité</td>
            <td style="text-align: center">Prix</td>
        </tr>
        {% for item in items %}#}
            <tr class="item">
                <td><span>{{ item.product.name }}</span></td>
                <td style="text-align: right"><span>{{ item.product.price }} €</span></td>
                <td style="text-align: right"><span>{{ item.quantity }}</span></td>
                <td style="text-align: right"><span>{{ item.priceTotal }} €</span></td>
            </tr>
        {% endfor %}

        <tr class="">
            <td></td>
            <td></td>
            <td></td>
            <td><strong>Total: {{ invoice.priceTotal }} €</strong></td>
        </tr>
    </table>
    <aside>
            <h1><span>Merci de votre achat !</span></h1>
    </aside>
</div>
</body>
</html>

e-commerce/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
    <div class="columns">
        <div class="column is-2">
            {% include 'profile/menu.html.twig' %}
        </div>
        <div class="column">

                {{ form_start(form) }}
                <h1 class="title">{{ 'title.registration'|trans }}</h1>

                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">{{ 'title.user_sexe'|trans }}</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <div class="control">
                                <div class="select is-fullwidth">
                                    {{ form_widget(form.gender, {'attr': {'class' : 'select is-fullwidth'}}) }}
                                    {{ form_errors(form.gender) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">{{ 'title.user_identity'|trans }}</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded has-icons-left">
                                {{ form_widget(form.surname, {'attr': {'class' : 'input'}}) }}
                                {{ form_errors(form.surname) }}
                                <span class="icon is-small is-left">
                              <i class="fas fa-user"></i>
                            </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control is-expanded has-icons-left has-icons-right">
                                {{ form_widget(form.lastname, {'attr': {'class' : 'input'}}) }}
                                {{ form_errors(form.lastname) }}
                                <span class="icon is-small is-left">
                              <i class="fas fa-user"></i>
                            </span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">{{ 'title.user_mail'|trans }}</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded has-icons-left has-icons-left">
                                {{ form_widget(form.email, {'attr': {'class' : 'input'}}) }}
                                {{ form_errors(form.email) }}
                                <span class="icon is-small is-left"><i class="far fa-envelope"></i></span>
                            </p>
                        </div>
                    </div>
                </div>



                <div class="field is-horizontal">
                    <div class="field-label">
                        <!-- Left empty for spacing -->
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <div class="control">
                                <button type="submit" class="button is-primary">
                                    {{ 'action.send'|trans }}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

e-commerce/templates/profile/invoice_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}

    <script src="https://code.jquery.com/jquery-3.3.1.js" type="application/javascript"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    {% include 'default/flash_message.html.twig' %}

    <div class="columns">
        <div class="column is-2">
            {% include 'profile/menu.html.twig' %}
        </div>
        <div class="column">

            <h1 class="title">{{ 'title.my_invoices'|trans }} :</h1>
                <table id="data" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <td>{{ 'title.date_invoice'|trans }}</td>
                            <td>{{ 'title.items_total'|trans }}</td>
                            <td>{{ 'title.price_total'|trans }}</td>
                            <td>{{ 'title.action'|trans }}</td>
                        </tr>
                    </thead>
                    <tbody>

                    {% if invoices is empty %}
                        <tr>
                            <td>Aucune facture !</td>
                        </tr>
                    {% else %}
                    {% for invoice in invoices %}
                        <tr>
                            <td>{{ invoice.createdAt | date("d/m/Y") }}</td>
                            <td>{{ invoice.itemsTotal }}</td>
                            <td>{{ invoice.priceTotal }} €</td>
                            <td><a href="{{ path('profile_download_invoice', {'id': invoice.id }) }}">{{ 'action.download_pdf'|trans }}</a></td>
                        </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <td>{{ 'title.date_invoice'|trans }}</td>
                        <td>{{ 'title.items_total'|trans }}</td>
                        <td>{{ 'title.price_total'|trans }}</td>
                        <td>{{ 'title.action'|trans }}</td>
                    </tr>
                    </tfoot>
                </table>
        </div>
    </div>

    <script type="application/javascript">
        $(document).ready(function() {
            $('#data').DataTable();
        } );
    </script>

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" type="application/javascript"></script>
{% endblock %}

e-commerce/templates/profile/menu.html.twig
<aside class="menu">
    {% set route = app.request.attributes.get('_route') %}
{#    <ul class="menu-list">#}
{#        <li><a>Dashboard</a></li>#}
{#    </ul>#}
    <p class="menu-label">
        General
    </p>
    <ul class="menu-list">
        <li>
            <a>{{ 'profile.manage_information'|trans }}</a>
            <ul>
                <li><a class="{{ 'profile_index' in route ? 'is-active' }}" href="{{ path('profile_index') }}">{{ 'profile.personnal_information'|trans }}</a></li>
                <li><a class="{{ 'profile_password' in route ? 'is-active' }}" href="{{ path('profile_password') }}">{{ 'profile.manage_information'|trans }}</a></li>
            </ul>
        </li>
    </ul>
    <p class="menu-label">
        Transactions
    </p>
    <ul class="menu-list">
        <li><a class="{{ 'profile_invoice' in route ? 'is-active' }}" href="{{ path('profile_invoice') }}">{{ 'title.my_invoices'|trans }}</a></li>
{#        <a href="{{absolute_url(path('resetting', {'id': user.id, 'token': user.token}))}}">Changer le mot de passe</a>#}
    </ul>
</aside>

e-commerce/templates/profile/password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
    {% include 'default/flash_message.html.twig' %}

    <div class="columns">
        <div class="column is-2">
            {% include 'profile/menu.html.twig' %}
        </div>
        <div class="column">

            {{ form_start(formPassword) }}
            <h1 class="title">{{ 'profile.change_password'|trans }}</h1>

            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">{{ 'profile.old_password'|trans }}</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <p class="control">
                            {{ form_widget(formPassword.oldPassword, {'attr': {'class' : 'input'}}) }}
                            {{ form_errors(formPassword.oldPassword, {'attr': {'class' : 'has-text-danger'}}) }}
                        </p>
                    </div>
                </div>
            </div>

            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">{{ 'profile.new_password'|trans }}</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <p class="control">
                            {{ form_widget(formPassword.newPassword , {'attr': {'class' : 'input'}}) }}
                            {{ form_errors(formPassword.newPassword, {'attr': {'class' : 'has-text-danger'}}) }}
                        </p>
                    </div>
                </div>
            </div>

            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">{{ 'profile.confirm_password'|trans }}</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <p class="control">
                            {{ form_widget(formPassword.confirmPassword, {'attr': {'class' : 'input'}}) }}
                            {{ form_errors(formPassword.confirmPassword, {'attr': {'class' : 'has-text-danger'}}) }}
                        </p>
                    </div>
                </div>
            </div>


            <div class="field is-horizontal">
                <div class="field-label">
                    <!-- Left empty for spacing -->
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-primary">
                                {{ 'action.send'|trans }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {{ form_end(formPassword) }}


        </div>
    </div>
{% endblock %}